### ISSUE TITLE
Some anvil drop recipes don't work

### ISSUE THREAD

**Issue by daemonspring** [Elmartino4/mechanical-factory#4]
Recipes that don't work:
  - `Ice + Ice + Ice -> Packed Ice`
  - `Mossy Cobblestone + Ice -> Prismarine`
  - `Ice  + Mossy Cobblestone -> Prismarine`
  - `Chiselled Stone Bricks -> Stone Bricks` Listed in the README, but doesn't exist in [MechanicalFactory.java]

The common factor seems to be `Ice`. I didn't test the `Frosted Ice + Frosted Ice + Frosted Ice -> Ice` recipe because I'm not sure how to get Frosted Ice.

[MechanicalFactory.java]: https://github.com/Elmartino4/mechanical-factory/blob/1.17/src/main/java/github/elmartino4/mechanicalfactory/MechanicalFactory.java

**Comment by Elmartino4** [comment]
I've tested, and found that these recipes work fine
* `Ice + Ice + Ice -> Packed Ice`
* `Mossy Cobblestone + Ice -> Prismarine`
* `Ice + Mossy Cobblestone -> Prismarine`

I'm not sure how I should reproduce your results.

I will be removing `Chiselled Stone Bricks -> Stone Bricks` from the REAMD.md

**Comment by daemonspring** [comment]
My apologies, it turns out another mod ([fabric-seasons]) is responsible for the problem. I didn't think any of the loaded mods touched anything related. I should have tested everything in isolation in the first place.

[fabric-seasons] introduces a [seasonal ice block] (and other seasonal variant blocks), which seems likely to be the problem. If the ice blocks are actually replaced with a different block, then they won't match the defined recipe. Seasonal ice extends regular ice though, so this makes me think you might be able to broadly improve compatibility by considering a subclass to be a match instead of only the exact types.

[fabric-seasons]: https://github.com/lucaargolo/fabric-seasons
[seasonal ice block]: https://github.com/lucaargolo/fabric-seasons/blob/1.17/src/main/java/io/github/lucaargolo/seasons/block/SeasonalIceBlock.java

**Comment by Elmartino4** [comment]
I'm unsure as to what the best way to go about this would be, without writing additional code (where I'd check extensions of classes) for this specific use case.
Maybe I could add compatibility to this mod by referring to blocks through a string from one or many json files (see #5 )

**Comment by daemonspring** [comment]
After some thought, the issue here might be a timing issue. If your initialization code stores a reference to a block type before fabric-seasons makes its changes, then that stored reference will refer to the original out of date block type by the time a world is loaded.

The best solution is to implement #5 so that you start storing identifiers like `"minecraft:ice"` instead of direct references. The identifiers will never be out of date. You can either compare blocks by their identifier, or get the blocks from the registry via their identifier.

fabric-seasons seems to update `minecraft:ice` rather than introducing its own new identifier, so it wouldn't even need a special config to make it work.

**Comment by Elmartino4** [comment]
I will be closing this issue and moving all related discussions to #5
