### ISSUE TITLE
Block36 (minecraft:moving_piston) protected anvils work in crushing recipes.

### ISSUE THREAD

**Issue by CodeF53** [Elmartino4/mechanical-factory#9]
This was a problem for a similar mod, so I tested it with this one and it worked.
https://www.youtube.com/watch?v=s15Wcw60jhQ

**Comment by CodeF53** [comment]
Here is a video of me explaining the mechanics behind this, and a test world so you can easily recreate the issue.
[MF-#9.zip](https://github.com/Elmartino4/mechanical-factory/files/8126913/MF-.9.zip)

https://youtu.be/EITLbjxghuc

**Comment by CodeF53** [comment]
I am pretty sure this is the commit to carpet extra that fixed this issue
https://github.com/gnembon/carpet-extra/commit/cf6c7db91d6a6bbb3804002d331cbb8927b11f7b

**Comment by Elmartino4** [comment]
Thanks for the helpful video, and detailed issue report!
I will look into the commit to carpet extra you included, and a patch should be out shortly

**Comment by Elmartino4** [comment]
This has now been fixed in https://github.com/Elmartino4/mechanical-factory/commit/a4c1ac261f15c87138747fc54b5c0f4db26d32da an updated jar will be uploaded to https://modrinth.com/mod/mechafact shortly
